input:
    size: (224, 224)
model:
    name: 'Nasnetamobile'
    classes: 10
dataset:
    name: 'Skin10Dataset'
    dir: '../datasets/skin100_dataset/train'
    train_list: '../datasets/skin10_train.txt'
    valid_list: '../datasets/skin10_test.txt'
    test_list: '../datasets/skin10_test.txt'
    batch_size: 32
transforms:
    name: 'SkinTransforms'
    tensor:
        normalization: 
            mean: [0.6054, 0.4433, 0.4084]
            std: [0.2125, 0.1816, 0.1786]
    img:
        aug_cifar: False
        color_jitter:
            enable: 1
            brightness: 0.05
            contrast: 0.05
            saturation: 0.05
            hue: 0.05
optim:
    scheduler:
        milestones: [20, 40, 60, 80]
trainer:
    default_save_path: './output_skin100'
    logger:
        setting: 0
        type: 'test_tube'
        mlflow:
            tracking_uri: './output_skin100' 
        test_tube:
            save_dir: './output_skin100'
hooks:
    early_stopping:
        setting: 2
        patience: 20
        monitor: 'val_acc'
        mode: 'max'
    model_checkpoint:
        setting: 0
        filepath: './output_skin100'