input:
    size: (224, 224)
model:
    meta_arch: 'Resnet50'
    classes: 10
dataset:
    NAME: 'Skin10Dataset'
    dir: '../datasets/skin100_dataset/train'
    train_list: '../datasets/skin10_train.txt'
    valid_list: '../datasets/skin10_test.txt'
    test_list: '../datasets/skin10_test.txt'
    batch_size: 32
transforms:
    NAME: 'SkinTransforms'
    tensor:
        normalization: 
            mean: [0.6054, 0.4433, 0.4084]
            std: [0.2125, 0.1816, 0.1786]
    img:
        aug_cifar: False
        color_jitter:
            brightness: 0.05
            contrast: 0.05
            saturation: 0.05
            hue: 0.05
trainer:
    default_save_path: './output_skin100'
    logger:
        setting: 0
        type: 'test_tube'
        mlflow:
            tracking_uri: './output_skin100' 
        test_tube:
            save_dir: './output_skin100'
hooks:
    early-stopping:
        type: 2
        patience: 20
        monitor: 'val_loss'
        mode: 'min'
    model_checkpoint:
        type: 0
        filepath: './output_skin100'