input:
    size: (32, 32)
model:
    meta_arch: 'Resnet50'
    classes: 10
dataset:
    NAME: 'CIFAR10'
    dir: './datasets/cifar10'
    batch_size: 32
transforms:
    tensor:
        normalization: 
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    img:
        aug_cifar: True